global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'citysafesense'
    static_configs:
      - targets: ['heartbeat:8000','detector:8001','triangulation:8002','dispatcher:8003']

  - job_name: 'mosquitto'
    metrics_path: /metrics
    static_configs:
      - targets: ['mosquitto:9304']
